using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WebApiDemo.Models
{
    public class Rcbp1
    {
        [Key]
        public int TrxNo { get; set; }
        public string BusinessPartyCode { get; set; }
        public string BusinessPartyName { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerRequestBy { get; set; }
        public string VendorCode { get; set; }
        public string VendorRequestBy { get; set; }
        public string AcctNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string AgentName { get; set; }
        public string AgentAccCode { get; set; }
        public string AgentCityName { get; set; }
        public string AgentIataCode { get; set; }
        public string AirAgentCode { get; set; }
        public string AnalysisCode1 { get; set; }
        public string AnalysisCode2 { get; set; }
        public string AnalysisCode3 { get; set; }
        public string AppointAgentCode { get; set; }
        public string APCode { get; set; }
        public string APSalesCode { get; set; }
        public string ARAcctCode { get; set; }
        public string ARCode { get; set; }
        public string ARSalesCode { get; set; }
        public string AwbPrefix { get; set; }
        public Nullable<decimal> BBFeeAmount { get; set; }
        public string BBFeeCalculationMethod { get; set; }
        public string BBFeeCurrCode { get; set; }
        public string BillToCode { get; set; }
        public string BranchId { get; set; }
        public string BusinessType { get; set; }
        public string CfsChargeInstruction { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public string ColdCallFlag { get; set; }
        public string ColdCallRemark { get; set; }
        public string CompanyProfile { get; set; }
        public string ContactName1 { get; set; }
        public string ContactName2 { get; set; }
        public string ContactName3 { get; set; }
        public string CostCentreCode { get; set; }
        public string CountryCode { get; set; }
        public string CreditStatusCode { get; set; }
        public string CrNo { get; set; }
        public string CurrCode { get; set; }
        public string DatabaseName { get; set; }
        public string DeliveryToName { get; set; }
        public string DeliveryToAddress1 { get; set; }
        public string DeliveryToAddress2 { get; set; }
        public string DeliveryToAddress3 { get; set; }
        public string DeliveryToAddress4 { get; set; }
        public string DistrictCode { get; set; }
        public string DivisionCode { get; set; }
        public Nullable<byte> EdiCount { get; set; }
        public Nullable<System.DateTime> EdiDateTime { get; set; }
        public string Email { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Fax { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Fax3 { get; set; }
        public string FwbName { get; set; }
        public string FwbAccCode { get; set; }
        public string FwbAddress { get; set; }
        public string FwbPlace { get; set; }
        public string FwbState { get; set; }
        public string Handphone1 { get; set; }
        public string Handphone2 { get; set; }
        public string Handphone3 { get; set; }
        public string InsuranceBill { get; set; }
        public string InsuranceFlag { get; set; }
        public string JtcAccCode { get; set; }
        public string KnownShipperFlag { get; set; }
        public string LocalName { get; set; }
        public string Marking { get; set; }
        public string MinDef { get; set; }
        public string ModuleCode { get; set; }
        public string Network { get; set; }
        public string NominationFlag { get; set; }
        public string NominationRemark { get; set; }
        public string NominationRemark2 { get; set; }
        public string NominationRemark3 { get; set; }
        public string NominationTariffNote { get; set; }
        public string Note { get; set; }
        public string Pager1 { get; set; }
        public string Pager2 { get; set; }
        public string Pager3 { get; set; }
        public string PartyShortCode { get; set; }
        public string PartyType { get; set; }
        public string PartyTypeRemark { get; set; }
        public string Password { get; set; }
        public string PayType { get; set; }
        public string Place { get; set; }
        public string PostalCode { get; set; }
        public string PsaAccCode { get; set; }
        public string RACode { get; set; }
        public string RebateFlag { get; set; }
        public string Remark { get; set; }
        public string SalesLeadFlag { get; set; }
        public string SalesLeadRemark { get; set; }
        public string SalesmanCode { get; set; }
        public string SalesmanCode2 { get; set; }
        public string SalesmanCode3 { get; set; }
        public Nullable<System.DateTime> SatLunchFromTime { get; set; }
        public Nullable<System.DateTime> SatLunchToTime { get; set; }
        public Nullable<System.DateTime> SatWorkFromTime { get; set; }
        public Nullable<System.DateTime> SatWorkToTime { get; set; }
        public string SBUCode { get; set; }
        public string SectorCode { get; set; }
        public string ServerName { get; set; }
        public string SiteCode { get; set; }
        public string SpecialInstruction { get; set; }
        public string StateOrProvince { get; set; }
        public Nullable<System.DateTime> SunLunchFromTime { get; set; }
        public Nullable<System.DateTime> SunLunchToTime { get; set; }
        public Nullable<System.DateTime> SunWorkFromTime { get; set; }
        public Nullable<System.DateTime> SunWorkToTime { get; set; }
        public string TaxId { get; set; }
        public string Telephone { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string Telex { get; set; }
        public string TermCode { get; set; }
        public string Title1 { get; set; }
        public string Title2 { get; set; }
        public string Title3 { get; set; }
        public string TradenetAddress1 { get; set; }
        public string TradenetAddress2 { get; set; }
        public string TradenetName1 { get; set; }
        public string TradenetName2 { get; set; }
        public string VatCode { get; set; }
        public string WarehouseCode { get; set; }
        public string WebSite { get; set; }
        public Nullable<System.DateTime> WeekLunchFromTime { get; set; }
        public Nullable<System.DateTime> WeekLunchToTime { get; set; }
        public Nullable<System.DateTime> WeekWorkFromTime { get; set; }
        public Nullable<System.DateTime> WeekWorkToTime { get; set; }
        public string WorkStation { get; set; }
        public string StatusCode { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string AttachmentFlag { get; set; }
    }
}